#!/bin/bash

BEGINTIME=20060101
ENDTIME=20171030


find_events -b ${BEGINTIME} -e ${ENDTIME} -m 6 -D 50 \
    | awk '{print $4" "$2" "$1" "$3*1000" "$5}' > tmp

awk '{print $1}' tmp | awk 'BEGIN {FS="_"} {print $1$2$3$4$5}' > paste1

awk '{print $1}' tmp | awk 'BEGIN {FS="_"} {print $4" "$5" "$6"."$7}' > paste2

awk '{print $2" "$3" "$4}' tmp > paste3

awk '{print $5}' tmp | cut -c 1-3 > paste4

awk '{print $5}' tmp | cut -c 4- > paste5

paste paste1 paste2 paste3 paste4 paste5 > EVENTS

rm tmp paste1 paste2 paste3 paste4 paste5 > /dev/null 2>&1

exit 0
